### ISSUE TITLE
Import of BasedOn does not support TBD yet

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr-text-import#3] opened 2017-02-27 22:26 UTC
It looks like importing TBDs associated with based on for a data element just gets an identifier object with type set to Identifier and no other attributes. the text value is lost. From the SubstanceAbuseTreatment data element in behavior:

Based on:		TBD "Program"

results in:

              "basedOn": [
                {
                  "type": "Identifier"
                }]

in the model

**Comment by cmoesel** [comment] 2017-03-27 18:56
Perhaps this was in an older version of the SHR importer, but I cannot reproduce this in my current grammar_4.2 branch (and I don't recall making any fixes for it).  Will check in a unit test to prove it shortly.

**Comment by gregquinn2001** [comment] 2017-03-27 18:57
I thought I made sure I had the latest, but I will double check again for you. Sorry about the false alarm if so, but at least it will improve our unit test suite maybe!

**Comment by cmoesel** [comment] 2017-03-27 19:38
You might want to check to be sure it's not an exporter bug.  I think I *did* fix a bug like this in the MD/HTML exporter (improperly _exporting_ based-on TBDs), so it's possible there is a similar bug in the JSON exporter.

**Comment by gregquinn2001** [comment] 2017-03-27 19:40
I debugged in and looked at what the importer was providing via the model.

**Comment by cmoesel** [comment] 2017-04-07 17:53
Closing for now since I cannot reproduce.  Please re-open if you find the bug is still valid.

**Closed by cmoesel** 2017-04-07 17:53 UTC

**Comment by gregquinn2001** [comment] 2017-04-07 19:16
It looks like I'm getting the _text attribute in the basedOn object now for TBDs so I can update the exporter to support it. Not sure when it got fixed, but the model looks better now. thanks
